[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
call-from = "G1pmmxExNW5H3nBx4uNk45QZiFX6QcRKSA3KdUm2qgia"
call-to = "2fMXp5XgFHrrRqMgrPjxzh98LMuc79pXRC82KUdKgYKe"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


[test.validator]
url = "https://dark-intensive-dream.solana-mainnet.quiknode.pro/bcea36be83c7f3b3e1afbb625fa47048926bf67f/"
