[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
instruction_patch_demo = "5zB1vCeQxFXkbFiucPB4XqDWTuDNo5FFFYLH54kUh3pR"


[registry]
url = "http://127.0.0.1:8899"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


[test.validator]
url = "https://dark-intensive-dream.solana-mainnet.quiknode.pro/bcea36be83c7f3b3e1afbb625fa47048926bf67f/"
