[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
call-from = "A45WqrL8wTCZ1DwhJpRbTWfnFsoGPirCwoRyEz75ZCBi"
call-to = "8p8DaKvzS2ELxUAXQjeeyghsHDv7UZubiTsshqPWvqfi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/qiang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
